services:

  app:
    build: .
    container_name: nutrition-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      # Override specific vars if needed (optional)
      CACHE_URL: ${CACHE_URL}
      CACHE_BACKEND: ${CACHE_BACKEND}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7.4-alpine
    container_name: nutrition_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    container_name: nutrition_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER": ${POSTGRES_USER}
      POSTGRES_PASSWORD": ${POSTGRES_PASSWORD}
      POSTGRES_DB": ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
