services:

  app:
    build: .
    container_name: nutrition-api-prod
    ports:
      - "80:8000"
    environment:
      - ENVIRONMENT=prod
      - CACHE_URL=redis://redis:6379
      - CACHE_BACKEND=redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes: []  # disable local code mounting

  redis:
    image: redis:7-alpine
    container_name: redis-prod
    ports: []  # no port exposed publicly, internal use only
